services:
  postgres:
    image: postgres:18.1
    container_name: postgres_pevs
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pevs_scraper_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_pevs:
      build: .
      image: etl_pevs:latest
      container_name: scraper_pevs
      command: ["python", "principal.py"]
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - pevs_scraper_net

volumes:
  pgdata:

networks:
  pevs_scraper_net:
    driver: bridge

